<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'BUREAU OPERATEUR DROIT EN BOIS 140x80x75',
                'slug' => 'bureau-operateur-droit-en-bois-140x80x75',
                'root' => 'mobilier-de-bureau',
                'category' => 'bureaux',
                'price' => 990.00,
                'quantity' => 8,
                'featured' => true,
                'description' => 'Bureau operateur pense pour open space, PME et cabinets de services au Maroc.',
            ],
            [
                'name' => 'FAUTEUIL OPERATEUR JUPITTER EN TISSU',
                'slug' => 'fauteuil-operateur-jupitter-en-tissu',
                'root' => 'mobilier-de-bureau',
                'category' => 'sieges-et-fauteuils',
                'price' => 720.00,
                'quantity' => 25,
                'featured' => true,
                'description' => 'Fauteuil reglable pour equipe administrative, accueil et postes de travail intensifs.',
            ],
            [
                'name' => 'FAUTEUIL VISITEUR D088 SUR LUGE CHROME',
                'slug' => 'fauteuil-visiteur-d088-sur-luge-chrome',
                'root' => 'mobilier-de-bureau',
                'category' => 'sieges-et-fauteuils',
                'price' => 510.00,
                'quantity' => 12,
                'featured' => true,
                'description' => 'Assise visiteur ideale pour salles d attente, reception et bureaux de direction.',
            ],
            [
                'name' => 'TABLE DE REUNION OVALE 10 PLACES',
                'slug' => 'table-de-reunion-ovale-10-places',
                'root' => 'mobilier-de-bureau',
                'category' => 'tables-de-reunion',
                'price' => 3490.00,
                'quantity' => 5,
                'featured' => true,
                'description' => 'Grande table pour reunions internes, negociations et comites de direction.',
            ],
            [
                'name' => 'ARMOIRE VESTIAIRE EN METAL 2 PORTES',
                'slug' => 'armoire-vestiaire-en-metal-2-portes',
                'root' => 'mobilier-de-bureau',
                'category' => 'meubles-de-rangement',
                'price' => 1070.00,
                'quantity' => 15,
                'featured' => false,
                'description' => 'Armoire metallique robuste pour archives, uniformes et zones techniques.',
            ],
            [
                'name' => 'CHAISE D ACCUEIL EMPILABLE NOIRE',
                'slug' => 'chaise-d-accueil-empilable-noire',
                'root' => 'mobilier-de-bureau',
                'category' => 'mobilier-d-accueil',
                'price' => 289.00,
                'quantity' => 40,
                'featured' => false,
                'description' => 'Chaise empilable pour accueil clients, salle de formation ou evenements professionnels.',
            ],
            [
                'name' => 'Ramette papier blanc grain toile A4 100g/m2 - 500 feuilles',
                'slug' => 'ramette-papier-blanc-grain-toile-a4-100g-m2-500-feuilles',
                'root' => 'papeterie',
                'category' => 'papiers-blancs-et-ivoires',
                'price' => 480.00,
                'quantity' => 500,
                'featured' => true,
                'description' => 'Papier premium pour rapports, impressions de presentation et correspondances professionnelles.',
            ],
            [
                'name' => 'Ramette papier Double A A4 80g/m2 - 500 feuilles',
                'slug' => 'ramette-papier-double-a-a4-80g-m2-500-feuilles',
                'root' => 'papeterie',
                'category' => 'papiers-blancs-et-ivoires',
                'price' => 74.50,
                'quantity' => 700,
                'featured' => false,
                'description' => 'Reference bureautique polyvalente pour administrations, ecoles et comptabilite.',
            ],
            [
                'name' => 'Papier couleur pastel A4 250 feuilles',
                'slug' => 'papier-couleur-pastel-a4-250-feuilles',
                'root' => 'papeterie',
                'category' => 'papiers-couleurs',
                'price' => 129.00,
                'quantity' => 200,
                'featured' => false,
                'description' => 'Papier couleur pour affichage interne, separation de dossiers et signaletique.',
            ],
            [
                'name' => 'Enveloppes commerciales auto-adhesives x100',
                'slug' => 'enveloppes-commerciales-auto-adhesives-x100',
                'root' => 'papeterie',
                'category' => 'courrier',
                'price' => 89.00,
                'quantity' => 150,
                'featured' => false,
                'description' => 'Enveloppes de courrier pour facturation, contrats et correspondance entreprise.',
            ],
            [
                'name' => 'Boite de 50 stylos a bille retractable BIC M10 Medium',
                'slug' => 'boite-de-50-stylos-a-bille-retractable-bic-m10-medium',
                'root' => 'fourniture-de-bureau',
                'category' => 'ecriture-correction',
                'price' => 179.00,
                'quantity' => 300,
                'featured' => true,
                'description' => 'Pack d ecriture fiable pour bureaux partages, ecoles et administrations.',
            ],
            [
                'name' => 'Classeur a levier A4 dos 80 mm',
                'slug' => 'classeur-a-levier-a4-dos-80-mm',
                'root' => 'fourniture-de-bureau',
                'category' => 'classement',
                'price' => 39.90,
                'quantity' => 400,
                'featured' => false,
                'description' => 'Classeur robuste pour archivage fiscal, administratif et RH.',
            ],
            [
                'name' => 'Cahier spirale A4 200 pages',
                'slug' => 'cahier-spirale-a4-200-pages',
                'root' => 'fourniture-de-bureau',
                'category' => 'cahiers-blocs-et-notes-adhesives',
                'price' => 54.90,
                'quantity' => 250,
                'featured' => false,
                'description' => 'Cahier grand format pour reunions, cours, briefing et prise de notes continue.',
            ],
            [
                'name' => 'Agrafeuse a pince KW-triO metallisee 25 feuilles',
                'slug' => 'agrafeuse-a-pince-kw-trio-metallisee-25-feuilles',
                'root' => 'fourniture-de-bureau',
                'category' => 'petite-fourniture',
                'price' => 55.00,
                'quantity' => 120,
                'featured' => false,
                'description' => 'Agrafeuse de bureau compacte pour documents, bons de commande et dossiers.',
            ],
            [
                'name' => 'Agenda professionnel 2026 A5',
                'slug' => 'agenda-professionnel-2026-a5',
                'root' => 'fourniture-de-bureau',
                'category' => 'agendas-et-calendriers',
                'price' => 68.00,
                'quantity' => 160,
                'featured' => false,
                'description' => 'Agenda pratique pour planification commerciale, rendez-vous et suivi d equipe.',
            ],
            [
                'name' => 'Machine a relier manuelle A4',
                'slug' => 'machine-a-relier-manuelle-a4',
                'root' => 'fourniture-de-bureau',
                'category' => 'machines-de-bureau',
                'price' => 890.00,
                'quantity' => 18,
                'featured' => false,
                'description' => 'Relieuse manuelle pour dossiers d appel d offres, supports de reunion et formation.',
            ],
            [
                'name' => 'PC Portable Pro 15 pouces i7 16Go 512Go SSD',
                'slug' => 'pc-portable-pro-15-pouces-i7-16go-512go-ssd',
                'root' => 'informatique-accessoires',
                'category' => 'ordinateurs-et-serveurs',
                'price' => 8999.00,
                'quantity' => 20,
                'featured' => true,
                'description' => 'Portable pro pour bureautique avancee, ERP, comptabilite et teletravail.',
            ],
            [
                'name' => 'Ecran LED 27 pouces Full HD',
                'slug' => 'ecran-led-27-pouces-full-hd',
                'root' => 'informatique-accessoires',
                'category' => 'ecrans',
                'price' => 2999.00,
                'quantity' => 30,
                'featured' => true,
                'description' => 'Moniteur confortable pour postes d accueil, gestion et production documentaire.',
            ],
            [
                'name' => 'Clavier et souris sans fil 2.4 GHz',
                'slug' => 'clavier-et-souris-sans-fil-2-4-ghz',
                'root' => 'informatique-accessoires',
                'category' => 'peripheriques',
                'price' => 349.00,
                'quantity' => 80,
                'featured' => false,
                'description' => 'Pack sans fil pour equiper rapidement des postes administratifs modernes.',
            ],
            [
                'name' => 'Imprimante multifonction laser couleur Wi-Fi',
                'slug' => 'imprimante-multifonction-laser-couleur-wi-fi',
                'root' => 'informatique-accessoires',
                'category' => 'imprimantes-et-multifonctions',
                'price' => 3499.00,
                'quantity' => 15,
                'featured' => false,
                'description' => 'Solution reseau pour PME, ecoles et structures de services avec fort volume d impression.',
            ],
            [
                'name' => 'Routeur Wi-Fi bi-bande entreprise',
                'slug' => 'routeur-wi-fi-bi-bande-entreprise',
                'root' => 'informatique-accessoires',
                'category' => 'reseau',
                'price' => 1190.00,
                'quantity' => 22,
                'featured' => false,
                'description' => 'Routeur pour bureaux, coworking et points de vente avec plusieurs utilisateurs.',
            ],
            [
                'name' => 'Onduleur 1000VA',
                'slug' => 'onduleur-1000va',
                'root' => 'informatique-accessoires',
                'category' => 'accessoires-informatiques',
                'price' => 1299.00,
                'quantity' => 25,
                'featured' => false,
                'description' => 'Protection electrique pour postes critiques, caisse et equipements reseau.',
            ],
            [
                'name' => 'Cartouche HP 305 Noir Originale',
                'slug' => 'cartouche-hp-305-noir-originale',
                'root' => 'cartouches-toners',
                'category' => 'cartouches-jet-d-encre',
                'price' => 199.00,
                'quantity' => 100,
                'featured' => false,
                'description' => 'Cartouche originale pour impressions nettes et stables en usage quotidien.',
            ],
            [
                'name' => 'Toner Laser HP 79A',
                'slug' => 'toner-laser-hp-79a',
                'root' => 'cartouches-toners',
                'category' => 'toner-pour-imprimantes-laser',
                'price' => 699.00,
                'quantity' => 40,
                'featured' => false,
                'description' => 'Toner pour cycle d impression professionnel regulier et documents internes.',
            ],
            [
                'name' => 'Gel hydroalcoolique 500 ml',
                'slug' => 'gel-hydroalcoolique-500-ml',
                'root' => 'services-generaux',
                'category' => 'hygiene',
                'price' => 49.00,
                'quantity' => 200,
                'featured' => false,
                'description' => 'Gel pour accueil, open space et zones de passage en entreprise.',
            ],
            [
                'name' => 'Distributeur papier essuie-mains mural ABS',
                'slug' => 'distributeur-papier-essuie-mains-mural-abs',
                'root' => 'services-generaux',
                'category' => 'hygiene',
                'price' => 399.00,
                'quantity' => 30,
                'featured' => false,
                'description' => 'Distributeur mural pour sanitaires, cuisines de bureau et espaces collectifs.',
            ],
            [
                'name' => 'Bouilloire inox 1.7 L salle de pause',
                'slug' => 'bouilloire-inox-1-7-l-salle-de-pause',
                'root' => 'services-generaux',
                'category' => 'alimentation-et-reception',
                'price' => 249.00,
                'quantity' => 28,
                'featured' => false,
                'description' => 'Bouilloire inox pour coin cafe, reception et pause equipe.',
            ],
        ];

        $rootProductImages = [
            'mobilier-de-bureau' => 'assets/products/product-mobilier.svg',
            'papeterie' => 'assets/products/product-papeterie.svg',
            'fourniture-de-bureau' => 'assets/products/product-fourniture.svg',
            'informatique-accessoires' => 'assets/products/product-informatique.svg',
            'cartouches-toners' => 'assets/products/product-cartouches.svg',
            'services-generaux' => 'assets/products/product-services.svg',
        ];

        foreach ($products as $productData) {
            $category = Category::query()
                ->where('slug', $productData['root'].'-'.$productData['category'])
                ->firstOrFail();

            Product::query()->updateOrCreate(
                ['slug' => $productData['slug']],
                [
                    'category_id' => $category->id,
                    'name' => $productData['name'],
                    'description' => $productData['description'],
                    'price' => $productData['price'],
                    'image' => $rootProductImages[$productData['root']],
                    'quantity' => $productData['quantity'],
                    'featured' => $productData['featured'],
                    'is_active' => true,
                ]
            );
        }
    }
}
